name: Deploy to Preprod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Run deployment script on droplet
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          cd /home/treetrackrunner
          ./deploy-preprod.sh
